{% set name = "msmbuilder" %}
{% set version = "3.8.0" %}
{% set sha256 = "cfa59ecc1154f5b9cac042b12ffb152a1914f3437395ff96b75de762a081487d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - msmb = msmbuilder.scripts.msmb:main
  skip: True  # [win and py<35]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - cython
    - numpy
    - mdtraj
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - scipy
    - pandas
    - six
    - mdtraj
    - scikit-learn
    - numpydoc
    - pytables
    - pyhmc
    - pyyaml
    - jinja2
    - fastcluster

test:
  imports:
    - msmbuilder
  commands:
    - msmb -h

about:
  home: http://msmbuilder.org
  license: LGPLv2.1+
  summary: 'Statistical models for Biomolecular Dynamics'

  description: |
      MSMBuilder is an application and python library. It builds statistical
      models for high-dimensional time-series. The particular focus of the
      package is on the analysis of atomistic simulations of biomolecular
      dynamics such as protein folding and conformational change.
  doc_url: http://msmbuilder.org
  dev_url: https://github.com/msmbuilder/msmbuilder

extra:
  recipe-maintainers:
    - mpharrigan
