{% set name = "msmbuilder" %}
{% set version = "3.7.0" %}
{% set sha256 = "4ed39c63a623957f2d5e5178d4b6cf76dbe3b214ae2f5f1dba59bf91eab81b9c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - msmb = msmbuilder.scripts.msmb:main
  skip: True  # [win and py<35]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - cython
    - numpy x.x
    - mdtraj
  run:
    - python
    - setuptools
    - numpy x.x
    - scipy
    - pandas
    - six
    - mdtraj
    - scikit-learn
    - numpydoc
    - pytables
    - pyhmc
    - pyyaml
    - jinja2
    - fastcluster

test:
  imports:
    - msmbuilder
  commands:
    - msmb -h

about:
  home: http://msmbuilder.org 
  license: LGPLv2.1+
  summary: 'Statistical models for Biomolecular Dynamics'

  description: |
      MSMBuilder is an application and python library. It builds statistical
      models for high-dimensional time-series. The particular focus of the
      package is on the analysis of atomistic simulations of biomolecular
      dynamics such as protein folding and conformational change.
  doc_url: http://msmbuilder.org
  dev_url: https://github.com/msmbuilder/msmbuilder

extra:
  recipe-maintainers:
    - mpharrigan
