travis:
  secure:
    BINSTAR_TOKEN: jZJMo+oGkHXEwPvfDGS2/7C8+hHLBEYEOYX5rHxGyum3OoNuaZxH5Ncy2AsAInvCvdGodloYWT6VN2FD8UIeFjRF1HKAQUXpyV1wfNtbsR11ivuMLt9TM/AEFctRhGJ6ckyp3SpEb8uI4B5gOjOcN8LISF779+zZ6T65OfVi0KDANfTeTX7sbrIeH+XhVnlj6TkzxGfI9Ekfez20I8E5mNj5J/ifOrFpHd6Fh83v77NY5mdopsKzJtphTEEj2GVXfTt7LZnc2hLBpZZA7OsEgHUnIAtfY1En2/9m36s1zKW0x5XDLQZhy6uplDHKkRSUDFSGigHSYx6GjPO0RK9D5xpIB8xCH7Yt+YllqU8Uq3Q6vA6qgpc5FicBaSmqU95JBDGDtKDRu7pMtKvMhI1Ww+MzZUO7n+8wq8HhtSCtw8tcYegkPgUMLrRInWUVI58mhcX82eiyEXnlfNj6YYR9ityH+rztJBXJ5LQG0b4K/8vEUn9QCZKDByUeTx4uwfrYW9Tjek1+Roh27iMI1rM9bdA+gKwg3cKf5lcmrn0FxG3wZ1f2jIovMYcxOEWCMEdBGhCrJGLaKIlHrlrGnKTvGBjAXfEfjic6iiFNj1BKuFUSpAAZMIssExn2COZWHjkCSqQ60BB9ZlXcUHWRaI4I5Oj6hNhVuW+x+qpAqUsnz5U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
