travis:
  secure:
    BINSTAR_TOKEN: Ox1BY1czmxVoVcn5xcFLpvq7+oY20k0SYUroFdyRvSoKvKDW3caNY+feNIfMwBDbHBrTz1P1KDI8KpXY9n+mD6dGDR3BO97PjTdQl32lgR6f2xFY/nqzgPI7aiacW9k8rg7E87YC6whUAJQ1odKdNcq+EeYHZg4vd8toTY1LYskYFoO3Tzjpc7I+jIMX9wiRL2qs3C81pdgUM6Z4GDYF13ifaNGlVaQwQSDgcjR1920DgvJAfndFTmlyhUu55ARRs2qzL8AgLayLKiPbTD1/fnd6p7NmfvgMvrtWKskFSPqZ44rmcyaUcIKjobddN8gHFgsj+AhAS3m22tTgsCgmmXY8zQn/rWuTcx1cSVTIr1qpCLXgEJi2e0r+ZyUjw6xpeGPLOpXwIPsmmq34gbC4hA5ILNGc6uVs0hRtRa1rU3DqHzHFBhDIi69Yxk49Z7FcUBkRZQ80k8ZQt2xIc2njkDylUMgeYMN7GYtXRNl1u595rqlCMOORGXrutHIWfIqZGGkDDGsCak/1bV3jkzXAcZCFf/H7DO++XQwLchPVblGfZnGOEhdTs3jYxomKNB9Qz4PXesBI+CXFAse8XUesJEP4y9y7yYn7gz8jyBSpwMmACfAwOal8trkof7njinX3+xaigd5rDHHt7leDJzsrrNZ8UXi3/fGLTEh5XumeFnE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
